// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiyb8MKslDI24yi5jLRduPsx471g0jPyk',
    appId: '1:574001282363:web:5d33dabc8d1a0fc0620b1e',
    messagingSenderId: '574001282363',
    projectId: 'margdarshak-345f4',
    authDomain: 'margdarshak-345f4.firebaseapp.com',
    storageBucket: 'margdarshak-345f4.firebasestorage.app',
    measurementId: 'G-9TJMW367Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSGMKun73sy1phMjiPe8fVdoEBmF9xvWE',
    appId: '1:574001282363:android:03d6266f718d7702620b1e',
    messagingSenderId: '574001282363',
    projectId: 'margdarshak-345f4',
    storageBucket: 'margdarshak-345f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoAhmHTS9WGr_X6oPEbe4onWgkDPTcTgA',
    appId: '1:574001282363:ios:75f6d0dc77f020b8620b1e',
    messagingSenderId: '574001282363',
    projectId: 'margdarshak-345f4',
    storageBucket: 'margdarshak-345f4.firebasestorage.app',
    iosBundleId: 'com.example.eduguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoAhmHTS9WGr_X6oPEbe4onWgkDPTcTgA',
    appId: '1:574001282363:ios:75f6d0dc77f020b8620b1e',
    messagingSenderId: '574001282363',
    projectId: 'margdarshak-345f4',
    storageBucket: 'margdarshak-345f4.firebasestorage.app',
    iosBundleId: 'com.example.eduguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQT4vSJjDR6vYInB-jfDQ5GtEsbXVFaIw',
    appId: '1:574001282363:web:596733caf7314a07620b1e',
    messagingSenderId: '574001282363',
    projectId: 'margdarshak-345f4',
    authDomain: 'margdarshak-345f4.firebaseapp.com',
    storageBucket: 'margdarshak-345f4.firebasestorage.app',
    measurementId: 'G-4DYR11R5TY',
  );

}